apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    - port: {{ .Values.ports.port }}
      name: "http"
      targetPort: {{ .Values.ports.port }}
      protocol: TCP